sudo: false
cache: pip
language: python
python:
  - 3.7
stages:
  - lint
  - docs
  - tests
jobs:
  include:
    # lint stage
    - stage: lint
      env: TOXENV=manifest
    - env: TOXENV=flake8
    # docs stage
    - stage: docs
      env: TOXENV=doc8
    - env: TOXENV=readme
    - env: TOXENV=docs
    - stage: tests
      env: TOXENV=py
install:
  - pip install tox
script:
  - tox
